// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajhCivTh5EqndHPuriRTWz
// Component: 5q3VtuV01uaq
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: ajhCivTh5EqndHPuriRTWz/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: 5q3VtuV01uaq/css
import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: qot8YaKnHWx5/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: HxrdBCuReH5J/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: I1gsw4WjfG9r/icon

export const PlasmicRating__VariantProps = new Array("rating");

export const PlasmicRating__ArgProps = new Array();

function PlasmicRating__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__gd5Ab, {
          [sty.svgrating_five__gd5AbC5Wcl]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__gd5AbB8Rd9]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__gd5AbYanC]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_half__gd5AbXxa7F]: hasVariant(
            variants,
            "rating",
            "half"
          ),

          [sty.svgrating_oneHalf__gd5AbXmqzh]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_one__gd5AbYt2NF]: hasVariant(
            variants,
            "rating",
            "one"
          ),

          [sty.svgrating_threeHalf__gd5AbcFtIu]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__gd5Abu4J6U]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__gd5Abo5Nhz]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__gd5Abm7Pnt]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__dbXyU, {
          [sty.svgrating_five__dbXyUc5Wcl]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__dbXyUb8Rd9]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__dbXyUyanC]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_oneHalf__dbXyUXmqzh]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_threeHalf__dbXyUcFtIu]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__dbXyUu4J6U]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__dbXyUo5Nhz]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__dbXyUm7Pnt]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__mCLrH, {
          [sty.svgrating_five__mCLrHc5Wcl]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__mCLrHb8Rd9]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__mCLrHyanC]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__mCLrHcFtIu]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__mCLrHu4J6U]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__mCLrHo5Nhz]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__mrzRk, {
          [sty.svgrating_five__mrzRkC5Wcl]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__mrzRkB8Rd9]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__mrzRkYanC]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__mrzRkcFtIu]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__nvZgS, {
          [sty.svgrating_five__nvZgSc5Wcl]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__nvZgSb8Rd9]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
