// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajhCivTh5EqndHPuriRTWz
// Component: 5FMOhlfEYvmi
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: S6Wqfi01Y7Bc/component
import Button from "../../Button"; // plasmic-import: 4qAucjeu1cAD/component
import ProductCard from "../../ProductCard"; // plasmic-import: Co67cSY-2KRJ/component
import Rating from "../../Rating"; // plasmic-import: 5q3VtuV01uaq/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: mWhqgZH-9w5v/component
import Value from "../../Value"; // plasmic-import: KtIqCA3kWXKA/component
import Footer from "../../Footer"; // plasmic-import: oHwEuPjwJkpq/component
import { useScreenVariants as useScreenVariants_3E952DoCYh3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 3_e952DoCYh3/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: ajhCivTh5EqndHPuriRTWz/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 5FMOhlfEYvmi/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: 4TThOMLJ45_Q/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: P6sKLCpgiDAA/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: aZA8iw3koaQT/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: Fjqg2pnQF8v2/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: wiPa5Z2XuGXq/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: oc227pQzuKa8/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: CVZB-k0Psnyy/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: rX9J4q73SOkJ/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: A25pE89Fz5IP/icon
import shoe14UQjKoLhSyFd from "./images/shoe14.png"; // plasmic-import: U-QjKoLHSyFd/picture
import shoe15TqRtedHcLvi from "./images/shoe15.png"; // plasmic-import: tqRtedHC-lvi/picture
import shoe166AbFoKuEhE9M from "./images/shoe16.png"; // plasmic-import: 6abFOKuEhE9M/picture
import shoe17V418Myw93CkE from "./images/shoe17.png"; // plasmic-import: v418myw93ckE/picture
import shoe18LYz8OhNnPfoH from "./images/shoe18.png"; // plasmic-import: LYz8OhNNPfoH/picture
import shoe19YHlxJtqGo83T from "./images/shoe19.png"; // plasmic-import: yHLXJtqGo83t/picture
import shoe8ReskBFzFxx from "./images/shoe8.png"; // plasmic-import: resk-bFZ-fxx/picture
import shoe70EwRGsouwq0L from "./images/shoe7.png"; // plasmic-import: 0EwRGsouwq0L/picture
import shoe6SEDsXFvFns1T from "./images/shoe6.png"; // plasmic-import: sEDsXFvFns1T/picture
import shoe5Ct4H3Xw0ZuYh from "./images/shoe5.png"; // plasmic-import: ct4h3xw0zuYh/picture
import shoe48Fy4GRlCEy8L from "./images/shoe4.png"; // plasmic-import: 8fy4GRlCEy8l/picture
import shoe33V2Rwo0Db3Th from "./images/shoe3.png"; // plasmic-import: 3V2RWO0db3th/picture
import shoe2XNfjsd3VmP5W from "./images/shoe2.png"; // plasmic-import: xNFJSD3vmP5W/picture
import shoe9IAlVaCUdSwf from "./images/shoe9.png"; // plasmic-import: iALVaC-udSwf/picture
import shoe10FMwjFcIKjcCo from "./images/shoe10.png"; // plasmic-import: fMwjFcIKjcCO/picture
import shoe115UqoOIdo0CxL from "./images/shoe11.png"; // plasmic-import: 5uqoOIdo0CxL/picture
import shoe1297LvKdReWxq5 from "./images/shoe12.png"; // plasmic-import: 97lvKdReWXQ5/picture
import shoe13PatyBmgHRpbu from "./images/shoe13.png"; // plasmic-import: PatyBmgHRpbu/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("container42");

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_3E952DoCYh3()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__mGm6)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___2Ajy)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qSiA)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection!"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r4J9W
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  className={classNames("__wab_instance", sty.button__vmL1)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__dGjuw)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  showEndIcon={true}
                  size={"large"}
                >
                  {"Shop"}
                </Button>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section___08YqT)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__az0Z5)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ebnar
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__ptD0)}
                  colors={"link"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__z0G9E)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                >
                  {"See more"}
                </Button>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__af9Zz)}
                img={{
                  src: shoe14UQjKoLhSyFd,
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__p5WyW)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x4L
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ykNue
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__cAUjO)}
                dollars={"79"}
                img={{
                  src: shoe15TqRtedHcLvi,
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___4RvP4)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6Nma
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mernN
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__kwdRy)}
                dollars={"64"}
                img={{
                  src: shoe166AbFoKuEhE9M,
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__fE31)}
                    rating={"two"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ujb2F
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lOa3
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__sak4V)}
                dollars={"99"}
                img={{
                  src: shoe17V418Myw93CkE,
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___3YUnS)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fkewz
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fkndy
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__yc4VW)}
                dollars={"79"}
                img={{
                  src: shoe18LYz8OhNnPfoH,
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__xDqIp)}
                    rating={"five"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jsbu
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m8Kfk
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard___23Wu)}
                dollars={"65"}
                img={{
                  src: shoe19YHlxJtqGo83T,
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__akRo)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__cljY)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ymZng)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vHl75)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nXmwt)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ttOuQ
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aupTy
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__awIp0)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xu5Uj
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <Button
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__sKuNd)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    size={"large"}
                  >
                    {"Shop sale"}
                  </Button>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__iifJe)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__op1Z8
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__yWkX)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___8DgzZ)}
                  icon={
                    <PlaneIcon
                      className={classNames(projectcss.all, sty.svg__nZr1Q)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qD7F
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lpIG
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__aoLy1)}>
                <Value
                  children2={
                    <Button
                      className={classNames("__wab_instance", sty.button__vKi0)}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__dutoO)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__ps6Vg)}
                  icon={
                    <DocumentIcon
                      className={classNames(projectcss.all, sty.svg__gIbp4)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nzeU4
                    )}
                  >
                    {"30-day guarantee"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dg4S
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__hGbw2)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__mabzv
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__ckiwp)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___91DI)}
                  icon={
                    <LockIcon
                      className={classNames(projectcss.all, sty.svg__jgZl)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aQ8Gx
                    )}
                  >
                    {"Secured payments"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xj3Xc
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </p.Stack>
          </EmojiValueProps>

          <section className={classNames(projectcss.all, sty.section__o0Coy)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jtOcx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gFdYu
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__r54OG
                      )}
                      colors={"link"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__fee9S)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sUdCs)}
              >
                <ProductCard
                  img={{
                    src: shoe14UQjKoLhSyFd,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eXs4
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sytNd
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xm1Xm
                  )}
                  img={{
                    src: shoe15TqRtedHcLvi,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hf9A
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__foIaa
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__l3FFs
                  )}
                  img={{
                    src: shoe166AbFoKuEhE9M,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vydEp
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hspRh
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__d1UYw
                  )}
                  img={{
                    src: shoe17V418Myw93CkE,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nNexT
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3URs4
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ic18A
                  )}
                  img={{
                    src: shoe18LYz8OhNnPfoH,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w9EnY
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fhBU
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mLfGj
                  )}
                  img={{
                    src: shoe19YHlxJtqGo83T,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__usqvI)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___4Vjv1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__otb5V
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__dTKl)}
                  states={"active"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y0IC
                    )}
                  >
                    {"All"}
                  </div>
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__f2M1)}
                >
                  {"New"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__gt0Ke)}
                >
                  {"Womens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__g8Fex)}
                >
                  {"Mens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__y6RXq)}
                >
                  {"Kids"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__c4KR)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uhFjt
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kfWr)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mheB5
                  )}
                  img={{
                    src: shoe8ReskBFzFxx,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ayhav
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Ozv0
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fNz0M
                  )}
                  img={{
                    src: shoe70EwRGsouwq0L,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sM7Yf
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bjsfT
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zc47O
                  )}
                  img={{
                    src: shoe6SEDsXFvFns1T,
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___73GBn
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6Le7L
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___3Y2Bt
                  )}
                  img={{
                    src: shoe5Ct4H3Xw0ZuYh,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dGm8W
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yX5Qx
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wt5G
                  )}
                  img={{
                    src: shoe48Fy4GRlCEy8L,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__srA
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sYwLr
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xsb0
                  )}
                  img={{
                    src: shoe33V2Rwo0Db3Th,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zLmf1
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__euOiv
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__f6Esl
                  )}
                  img={{
                    src: shoe2XNfjsd3VmP5W,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zna25
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Dsjb
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iupP
                  )}
                  img={{
                    src: shoe9IAlVaCUdSwf,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jEi0
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hxPAh
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sd8Sz
                  )}
                  img={{
                    src: shoe10FMwjFcIKjcCo,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__to0Jh
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aaJfg
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aiNqm
                  )}
                  img={{
                    src: shoe115UqoOIdo0CxL,
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__be4Rs
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uitWm
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__old4
                  )}
                  img={{
                    src: shoe1297LvKdReWxq5,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pQcp
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hnSfs
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bzj6G
                  )}
                  img={{
                    src: shoe13PatyBmgHRpbu,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5RFdf
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mF6Bz
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__vMqCa)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__uhoVl)}
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg___3Gk5D)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value___6ZuCm)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__aaIs)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Sx8L
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__evcd5
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(projectcss.all, sty.section__kTc3I)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__ykkX)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__cT2Bc
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__cbfBf)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__y16Hx)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__uss8U)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uRjym
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__prn1X
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__kKva4)}
                    colors={"link"}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__ungCl)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vftMu
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__lthIb)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___6Tnt7)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__twgmP)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__goA46
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gH2H
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__nJfvs)}
                    colors={"link"}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column__e7B1S)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__nb8Ol
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__nrIGk)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__ti75L)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__unNts)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t0JhR
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5KDn1
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__wfiAy)}
                    colors={"link"}
                  />
                </Value>
              </div>

              <div className={classNames(projectcss.all, sty.column___0Ji05)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__k8XbW
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__lv3Xg)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__qavdG)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__tdWv9)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d60Jr
                    )}
                  >
                    {"We give back for every sale."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e3UmG
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__qHqXw)}
                    colors={"link"}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],

  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
